{% set name = "Collectfast" %}
{% set version = "2.1.0" %}
{% set sha256 = "6e0ace218f908feec545ae30143d0a44457b4c61d7d3c35ff2ebf4f1fb8f4c41" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - django >=1.8
    - django-storages

test:
  imports:
    - collectfast

about:
  home: https://github.com/jazzband/collectfast
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: 'A Faster Collectstatic '
  description: |
    The fast collectstatic for Django projects with S3 as storage backend.
  doc_url: https://github.com/jazzband/collectfast
  dev_url: https://github.com/jazzband/collectfast

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
